### ISSUE TITLE
kpt-set mark removed from line after update to 1.0.0-beta.18

### ISSUE THREAD

**Issue by liamfallon** [liamfallon/porch-closed-issues#5]
Original issue URL: https://github.com/kptdev/kpt/issues/3405
Original issue user: https://github.com/RafalMaleska
Original issue state: closed
Original issue created at: 2022-07-22T12:44:34Z
Original issue last updated at: 2022-07-28T21:58:57Z
Original issue body: ### Expected behavior

`kpt pkg update`
 
```
apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /some-app
  name: some-app # kpt-set: ${some-app}
  labels:
  annotations:
    ncp/static_snat_ip: 122.122.122.122 # kpt-set: ${gateway-snat-ip}
```

### Actual behavior

`kpt pkg update`

```
apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /some-app
  name: some-app # kpt-set: ${some-app}
  labels:
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|some-app'
    ncp/static_snat_ip: 122.122.122.122
```

### Information

kpt version: 1.0.0-beta.18

After updating kpt to the newest version and using `kpt pkg update` a new annotation is added (as stated in the release notes). For some reason if there is another annotation which needs to be modified by a kpt function (kpt-set). The function mark is removed and the pipeline is ignoring this resource. 

Briefly: 

- before update the last line looked after kpt pkg update like: 
```
    ncp/static_snat_ip: 122.122.122.122 # kpt-set: ${gateway-snat-ip}
```
- after update to the newest version the last line is missing the # kpt-set

```
    ncp/static_snat_ip: 122.122.122.122 
```

Is it possible to not use the new kpt annotation? 
Is it a bug of kpt which causes the removal of this kpt-set mark?

### Steps to reproduce the behavior

kpt pkg update on an upstream resource which has an kpt-set function on an annotation. Tested this only with the namespace resource. 

Original issue comments: None
